const express=require('express'); const cors=require('cors');
function createApp({pool, jwt, bcrypt, jwtSecret}){
 const app=express(); app.use(cors({origin:true})); app.use(express.json({limit:'1mb'}));
 const auth=(req,res,next)=>{try{const h=req.headers.authorization||''; if(!h.startsWith('Bearer ')) return res.status(401).json({error:'Authentication required'}); req.user=jwt.verify(h.slice(7),jwtSecret); next()}catch(e){return res.status(401).json({error:'Invalid or expired token'})}};
 app.get('/api/health',(req,res)=>res.json({ok:true,service:'depositshield-api'}));
 app.post('/api/auth/register',async(req,res)=>{try{const {email,password,role}=req.body||{}; if(!email||!password||!['TENANT','LANDLORD'].includes(role)) return res.status(400).json({error:'email, password and valid role are required'}); if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters'}); const hash=await bcrypt.hash(password,12); const r=await pool.query('INSERT INTO users(email,password_hash,role) VALUES($1,$2,$3) RETURNING id,email,role',[email.toLowerCase(),hash,role]); res.status(201).json(r.rows[0])}catch(e){if(e.code==='23505')return res.status(409).json({error:'Email already registered'});res.status(500).json({error:'Registration failed'})}});
 app.post('/api/auth/login',async(req,res)=>{try{const {email,password}=req.body||{}; const r=await pool.query('SELECT * FROM users WHERE email=$1',[String(email||'').toLowerCase()]); if(!r.rowCount||!(await bcrypt.compare(password||'',r.rows[0].password_hash)))return res.status(401).json({error:'Invalid credentials'}); const u=r.rows[0]; const token=jwt.sign({id:u.id,email:u.email,role:u.role},jwtSecret,{expiresIn:'8h'});res.json({token,user:{id:u.id,email:u.email,role:u.role}})}catch(e){res.status(500).json({error:'Login failed'})}});
 app.post('/api/properties',auth,async(req,res)=>{if(req.user.role!=='LANDLORD')return res.status(403).json({error:'Landlord access required'}); const {address}=req.body||{}; if(!address)return res.status(400).json({error:'Address is required'}); const r=await pool.query('INSERT INTO properties(landlord_id,address) VALUES($1,$2) RETURNING *',[req.user.id,address]);res.status(201).json(r.rows[0])});
 app.post('/api/inspections',auth,async(req,res)=>{const {propertyId,tenantId}=req.body||{}; const p=await pool.query('SELECT * FROM properties WHERE id=$1',[propertyId]); if(!p.rowCount)return res.status(404).json({error:'Property not found'}); if(req.user.role==='LANDLORD'&&p.rows[0].landlord_id!==req.user.id)return res.status(403).json({error:'Not your property'}); const r=await pool.query('INSERT INTO inspections(property_id,tenant_id) VALUES($1,$2) RETURNING *',[propertyId,tenantId||null]);res.status(201).json(r.rows[0])});
 app.get('/api/inspections/:id',auth,async(req,res)=>{const r=await pool.query('SELECT i.*,p.address,p.landlord_id FROM inspections i JOIN properties p ON p.id=i.property_id WHERE i.id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({error:'Inspection not found'}); const x=r.rows[0]; if(req.user.role==='LANDLORD'&&x.landlord_id!==req.user.id || req.user.role==='TENANT'&&x.tenant_id!==req.user.id)return res.status(403).json({error:'Access denied'}); const photos=await pool.query('SELECT * FROM photos WHERE inspection_id=$1 ORDER BY captured_at,id',[req.params.id]);res.json({...x,photos:photos.rows})});
 app.post('/api/inspections/:id/photos',auth,async(req,res)=>{const {roomName,s3Url,sha256,notes,deviceOrientation}=req.body||{}; if(!roomName||!s3Url||!sha256)return res.status(400).json({error:'roomName, s3Url and sha256 are required'}); const i=await pool.query('SELECT i.*,p.landlord_id FROM inspections i JOIN properties p ON p.id=i.property_id WHERE i.id=$1',[req.params.id]);if(!i.rowCount)return res.status(404).json({error:'Inspection not found'}); if(i.rows[0].status!=='DRAFT')return res.status(409).json({error:'Inspection is locked'}); if(req.user.id!==i.rows[0].landlord_id&&req.user.id!==i.rows[0].tenant_id)return res.status(403).json({error:'Access denied'}); const r=await pool.query('INSERT INTO photos(inspection_id,room_name,s3_url,sha256,notes,device_orientation) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[req.params.id,roomName,s3Url,sha256,notes||null,deviceOrientation||null]);res.status(201).json(r.rows[0])});
 app.post('/api/inspections/:id/sign',auth,async(req,res)=>{const i=await pool.query('SELECT i.*,p.landlord_id FROM inspections i JOIN properties p ON p.id=i.property_id WHERE i.id=$1',[req.params.id]);if(!i.rowCount)return res.status(404).json({error:'Inspection not found'});const x=i.rows[0];if(req.user.id!==x.landlord_id&&req.user.id!==x.tenant_id)return res.status(403).json({error:'Access denied'});if(x.status!=='DRAFT')return res.status(409).json({error:'Inspection already locked'});const sig=String(req.body.signature||'');if(!sig)return res.status(400).json({error:'Signature is required'});const col=req.user.id===x.landlord_id?'landlord_signature':'tenant_signature'; await pool.query(`UPDATE inspections SET ${col}=$1 WHERE id=$2`,[sig,req.params.id]); const rr=await pool.query('SELECT landlord_signature,tenant_signature FROM inspections WHERE id=$1',[req.params.id]); if(rr.rows[0].landlord_signature&&rr.rows[0].tenant_signature){const photos=await pool.query('SELECT id,room_name,s3_url,sha256,captured_at,notes,device_orientation FROM photos WHERE inspection_id=$1 ORDER BY captured_at,id',[req.params.id]);const crypto=require('crypto');const payload=JSON.stringify({inspectionId:req.params.id,photos:photos.rows,signatures:rr.rows[0]});const hash=crypto.createHash('sha256').update(payload).digest('hex');await pool.query('UPDATE inspections SET status=\'LOCKED\',final_hash=$1,locked_at=NOW() WHERE id=$2',[hash,req.params.id]);return res.json({status:'LOCKED',finalHash:hash})}res.json({status:'WAITING_FOR_OTHER_SIGNATURE'})});
 app.use((err,req,res,next)=>res.status(500).json({error:'Internal server error'})); return app;
}
module.exports={createApp};
